"""
main.py - FastAPI application entry point.

Defines all HTTP routes and wires the backend together.
Run locally with:
    uvicorn main:app --reload --port 8000

API endpoints:
    GET  /                  → health check (used by cloud platforms)
    POST /auth/register     → create account
    POST /auth/login        → get JWT token
    POST /agent/run         → run the farm agent (authenticated)
    GET  /agent/history     → retrieve past decisions (authenticated)
    GET  /docs              → interactive API docs (auto-generated by FastAPI)
"""

import sys
import os

# Allow imports from the backend directory itself
sys.path.insert(0, os.path.dirname(__file__))

from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from auth    import register_user, login_user, get_current_user
from agent   import FarmAgent
from models  import (
    RegisterRequest, LoginRequest, TokenResponse,
    RunRequest, RunResponse, WeatherSnapshot,
    HistoryResponse, HistoryEntry,
)
from database import users_collection, memories_collection

# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------
app = FastAPI(
    title       = "AgriSense Agent API",
    description = "AI-powered farm decision agent for smallholder farmers",
    version     = "1.0.0",
)

# ── CORS ─────────────────────────────────────────────────────────────────────
# Allows the Streamlit frontend (port 8501) to call this API (port 8000).
# In production, replace "*" with your actual Streamlit Cloud URL.
app.add_middleware(
    CORSMiddleware,
    allow_origins     = ["*"],
    allow_credentials = True,
    allow_methods     = ["*"],
    allow_headers     = ["*"],
)


# ---------------------------------------------------------------------------
# Startup: create MongoDB indexes
# Indexes make queries fast. Without them, MongoDB does a full collection scan.
# We create them once at startup - MongoDB is idempotent about this (safe to
# call even if they already exist).
# ---------------------------------------------------------------------------
@app.on_event("startup")
async def create_indexes():
    await users_collection.create_index("email",   unique=True)
    await memories_collection.create_index("user_id", unique=True)


# ---------------------------------------------------------------------------
# Health check
# Cloud platforms (Railway, Render, Fly.io) ping this endpoint to confirm
# the service is alive before routing real traffic to it.
# ---------------------------------------------------------------------------
@app.get("/", tags=["Health"])
async def health_check():
    return {"status": "ok", "service": "AgriSense Agent API"}


# ---------------------------------------------------------------------------
# Auth routes
# ---------------------------------------------------------------------------

@app.post("/auth/register", tags=["Auth"])
async def register(body: RegisterRequest):
    """
    Create a new user account.
    Returns an error if the email is already registered.
    """
    return await register_user(body.email, body.password)


@app.post("/auth/login", response_model=TokenResponse, tags=["Auth"])
async def login(body: LoginRequest):
    """
    Log in with email + password.
    Returns a JWT access token valid for ACCESS_TOKEN_EXPIRE_MINUTES minutes.
    Include this token in subsequent requests as:
        Authorization: Bearer <token>
    """
    return await login_user(body.email, body.password)


# ---------------------------------------------------------------------------
# Agent routes (all require authentication)
# ---------------------------------------------------------------------------

@app.post("/agent/run", response_model=RunResponse, tags=["Agent"])
async def run_agent(
    body:       RunRequest,
    user_email: str = Depends(get_current_user),   # JWT verified here
):
    """
    Run the AgriSense agent for a given crop, location, and growth stage.

    Pipeline:
        1. Fetch live weather from Open-Meteo
        2. Apply agronomy rule engine (crop + stage aware)
        3. Gemini synthesises a farmer-friendly summary
        4. Result saved to user's MongoDB memory

    Requires: Authorization: Bearer <token>
    """
    agent  = FarmAgent(user_id=user_email)
    result = await agent.run_agent(
        crop     = body.crop,
        location = body.location,
        stage    = body.stage,
    )

    # Weather fetch failed (location not found, network error, etc.)
    # agent.py returns temp=None as the sentinel for this case.
    # Raising 422 here means the frontend's existing "detail" error path fires
    # instead of falling through silently to the success renderer.
    if result["weather"].get("temp") is None:
        raise HTTPException(status_code=422, detail=result["llm_summary"])

    return RunResponse(
        crop         = result["crop"],
        location     = result["location"],
        stage        = result["stage"],
        weather      = WeatherSnapshot(**result["weather"]),
        actions      = result["actions"],
        explanations = result["explanations"],
        llm_summary  = result["llm_summary"],
    )


@app.get("/agent/history", response_model=HistoryResponse, tags=["Agent"])
async def get_history(
    n:          int = 5,
    user_email: str = Depends(get_current_user),
):
    """
    Retrieve the authenticated user's last n farm decisions.
    Defaults to the last 5 entries.

    Requires: Authorization: Bearer <token>
    """
    agent   = FarmAgent(user_id=user_email)
    entries = await agent.get_history(n_last=n)

    return HistoryResponse(
        user_id = user_email,
        history = [HistoryEntry(**e) for e in entries],
    )
